# Generated by Django 6.0.1 on 2026-01-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(help_text='Coursera, Udemy, etc.', max_length=200)),
                ('description', models.TextField()),
                ('date_obtained', models.DateField()),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('certificate_url', models.URLField(blank=True, help_text='Link to the online cerificate', null=True)),
            ],
            options={
                'ordering': ['-date_obtained'],
            },
        ),
    ]
